name: target-go-server

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: target-api 
    ports:
      - "3333:3333"
    volumes:
      - .:/go/src/app
  pg:
    image: bitnami/postgresql:13.16.0
    container_name: target-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
